### ISSUE TITLE
[BUG] - Problema en la edición de una anuncio completo

### ISSUE THREAD

**Issue by borpincal** [ISPP23-G11/FitWin#183]
### Description

Si un anuncio está completo queda inutilizada su edición ya que sale error de que los huecos libres no pueden ser 0. O aumentas el aforo o no puedes cambiarlo. Además en esta vista aparece duplicado los errores.

### Reproduction steps

```bash
1. Crea un anuncio con capacidad 1
2. Reserva el anuncio con un cliente
3. Dirígete a la edición del anuncio
4. Intenta editar algo sin modificar la capacidad
```

### OS

Linux

**Comment by raugalroc** [comment]
He creado una función 'validate_edit_announcement' similar a 'validate_announcement' pero sin la restriccion de capacidad
