### ISSUE TITLE
[BUG] - Si no tiene valoración => None

### ISSUE THREAD

**Issue by pabramber** [ISPP23-G11/FitWin#200]
### Description

Si un entrenador no tiene valoración, en los anuncios se muestra como None (pudiendo, en su defecto, ser 0)

### Reproduction steps

```bash
1. Crear anuncio con entrenador sin valoración
2. Ver dicho anuncio como otro cliente cualquiera
```

### Screenshots

```bash
No
```

### Browsers

Firefox

### OS

Windows

**Comment by albert011** [comment]
Se ha resuelto en el commit 6620cebd6a20854e3149e44f2fe79dcc0fd8d174 mediante un if/else en el template de list_announcements para que tenga valor por defecto 0 si detecta como 'None' el avg_rating asociado al trainer
